Repository ceph/teuthology, pull requests merged in 2019-11, with the labels that each got.

#1339 repo_utils: support github pull request branches
  teuthology/misc.py
  teuthology/repo_utils.py
Labels: feature

#1331 python3: use compatible urllib packages
  teuthology/lock/query.py
  teuthology/misc.py
  teuthology/packaging.py
  teuthology/provision/cloud/openstack.py
  teuthology/provision/cloud/test/test_openstack.py
  teuthology/task/kernel.py
  teuthology/task/pcp.py
  teuthology/test/task/test_pcp.py
  teuthology/util/compat.py
Labels: py3-migration

#1353 orchestra/run: more concise logging when we run commands
  teuthology/orchestra/run.py
Labels: improvement, needs-qa

#1355 make matrix py3 compatible
  teuthology/openstack/__init__.py
  teuthology/orchestra/remote.py
  teuthology/provision/__init__.py
  teuthology/provision/cloud/__init__.py
  teuthology/provision/cloud/openstack.py
  teuthology/suite/__init__.py
  teuthology/suite/build_matrix.py
  teuthology/suite/matrix.py
Labels: py3-migration

#1359 use remote sh instead run
  teuthology/orchestra/remote.py
  teuthology/orchestra/test/util.py
Labels: py3-migration

#1360 ceph_ansible: make code py3 compatible
  teuthology/task/ansible.py
  teuthology/task/ceph_ansible.py
  teuthology/task/install/__init__.py
  teuthology/task/internal/__init__.py
  teuthology/task/kernel.py
  teuthology/test/task/__init__.py
  teuthology/test/task/test_ansible.py
  teuthology/test/task/test_ceph_ansible.py
  teuthology/test/task/test_install.py
  teuthology/test/task/test_selinux.py
Labels: py3-migration

#1364 make cloud openstack py3 compatible
  teuthology/misc.py
  teuthology/openstack/__init__.py
  teuthology/orchestra/run.py
  teuthology/packaging.py
  teuthology/parallel.py
  teuthology/provision/cloud/openstack.py
  teuthology/provision/cloud/test/test_cloud_init.py
  teuthology/provision/cloud/test/test_cloud_util.py
  teuthology/provision/cloud/util.py
  teuthology/report.py
  teuthology/suite/matrix.py
  teuthology/suite/test/test_build_matrix.py
  teuthology/suite/util.py
  teuthology/test/test_contextutil.py
  teuthology/test/test_describe_tests.py
  teuthology/test/test_run.py
  teuthology/test/test_timer.py
Labels: py3-migration

#1361 remove circular imports
  teuthology/lock/__init__.py
  teuthology/lock/cli.py
  teuthology/lock/keys.py
  teuthology/lock/ops.py
  teuthology/orchestra/console.py
  teuthology/orchestra/remote.py
  teuthology/task/internal/lock_machines.py
Labels: improvement, py3-migration, test
