Repository ceph/teuthology, pull requests merged in 2019-12, with the labels that each got.

#1367 update/cleanup dependencies
  docs/INSTALL.rst
  requirements.in
  requirements.txt
  setup.py
Labels: deploy-test

#1374 valgrind.supp is used from ceph/qa
  setup.py
Labels: needs-qa, needs-smoke-testing

#1382 py3: cast dict keys to list
  teuthology/lock/ops.py
  teuthology/misc.py
  teuthology/nuke/__init__.py
  teuthology/orchestra/connection.py
  teuthology/provision/cloud/__init__.py
  teuthology/prune.py
  teuthology/task/internal/__init__.py
  teuthology/task/internal/syslog.py
  teuthology/task/internal/vm_setup.py
  teuthology/task/iscsi.py
  teuthology/task/kernel.py
  teuthology/test/fake_fs.py
  teuthology/test/test_ls.py
  teuthology/test/test_misc.py
  teuthology/test/test_report.py
  teuthology/worker.py
  tox.ini
Labels: py3-migration
