Repository ceph/teuthology, pull requests merged in 2020-04, with the labels that each got.

#1437 teuthology, tasks: fix dict related py3 compatibility issues
  teuthology/lock/ops.py
  teuthology/openstack/test/openstack-integration.py
  teuthology/task/background_exec.py
  teuthology/task/hadoop.py
Labels: deploy-test

#1440 added rhbuild attribute for redhat task and changes to retrieve correct daemon pid.
  teuthology/orchestra/daemon/systemd.py
  teuthology/task/internal/redhat.py
Labels: rh-qe-downstream

#1441 extra_packages and extra_system_packages added to redhat install task
  teuthology/task/install/__init__.py
  teuthology/task/install/redhat.py
Labels: rh-qe-downstream

#1442 updated config error exception w.r.t rhbuild
  teuthology/task/internal/redhat.py
Labels: rh-qe-downstream

#1445 teuthology: pass integer as "tries" to safe_while()
  teuthology/misc.py
  teuthology/orchestra/run.py
Labels: py3-migration

#1422 enable py3
  bootstrap
Labels: py3-migration

#1446 code changes for multiple rgw daemons in single host
  teuthology/orchestra/daemon/systemd.py
  teuthology/task/ceph_ansible.py
Labels: rh-qe-downstream

#1447 Enables grafana-server role to be added to inventory file
  teuthology/task/ceph_ansible.py
Labels: rh-qe-downstream

#1449 lock/cli: fix broken teuthology-lock --summary for py3
  teuthology/lock/cli.py
Labels: py3-migration

#1455 code changes w.r.t ceph ansible cluster-name
  teuthology/task/ceph_ansible.py
Labels: rh-qe-downstream

#1461 generate polarion frag-ids
  scripts/polarion.py
  setup.py
  teuthology/polarion/__init__.py
  teuthology/polarion/frag_id.py
  teuthology/polarion/util.py
  teuthology/polarion/write.py
Labels: rh-qe-downstream

#1462 cephadmunit: Python3 fix: signal.SIGHUP is no longer an int.
  teuthology/orchestra/daemon/cephadmunit.py
Labels: deploy-test-py3, py3-migration
