Repository ceph/teuthology, pull requests merged in 2020-03, with the labels that each got.

#1372 provision: add Pelagos support
  docs/siteconfig.rst
  teuthology/lock/cli.py
  teuthology/lock/ops.py
  teuthology/nuke/__init__.py
  teuthology/provision/__init__.py
  teuthology/provision/pelagos.py
  teuthology/provision/test/test_init_provision.py
  teuthology/provision/test/test_pelagos.py
Labels: needs-smoke-testing

#1416 Handles enabling of rhel 7 repos for RHCS 3.x and 4.x
  teuthology/task/ceph_ansible.py
  teuthology/task/internal/redhat.py
Labels: rh-qe-downstream

#1362 py3 compatibility
  bootstrap
  scripts/test/script.py
  teuthology/__init__.py
  teuthology/kill.py
  teuthology/misc.py
  teuthology/orchestra/daemon/systemd.py
  teuthology/orchestra/remote.py
  teuthology/orchestra/run.py
  teuthology/orchestra/test/test_remote.py
  teuthology/orchestra/test/test_run.py
  teuthology/packaging.py
  teuthology/provision/cloud/base.py
  teuthology/provision/cloud/util.py
  teuthology/repo_utils.py
  teuthology/suite/placeholder.py
  teuthology/suite/run.py
  teuthology/suite/test/test_run_.py
  teuthology/suite/util.py
  teuthology/task/__init__.py
  teuthology/task/install/deb.py
  teuthology/task/kernel.py
  teuthology/task/mpi.py
  teuthology/task/pcp.py
  teuthology/task/selinux.py
  teuthology/test/task/test_ansible.py
  tox.ini
Labels: py3-migration

#1435 teuthology/task/install
  teuthology/task/install/__init__.py
Labels: rh-qe-downstream
