Repository ceph/teuthology, pull requests merged in 2020-05, with the labels that each got.

#1366 suite: add filter-all parameter
  scripts/suite.py
  teuthology/suite/__init__.py
  teuthology/suite/run.py
Labels: improvement

#1474 teuthology/run_tasks: do not call sys.exc_clear() for clearing exception
  teuthology/run_tasks.py
Labels: py3-migration

#1499 orchestra/run: py2 fix for copy_and_close
  teuthology/orchestra/run.py
  teuthology/orchestra/test/test_run.py
Labels: deploy-test, needs-qa
