Repository ceph/teuthology, pull requests merged in 2022-07, with the labels that each got.

#1777 suite/run: Log total number of jobs scheduled
  teuthology/suite/run.py
Labels: improvement

#1776 teuthology: add pre/post fragment merge hooks
  docs/fragment_merging.rst
  docs/index.rst
  scripts/schedule.py
  setup.cfg
  teuthology/describe_tests.py
  teuthology/misc.py
  teuthology/suite/fragment-merge.lua
  teuthology/suite/merge.py
  teuthology/suite/run.py
  teuthology/suite/test/test_merge.py
  teuthology/suite/test/test_run_.py
  teuthology/suite/util.py
Labels: feature, needs-review

#1778 suite: Do not send emails with --dry-run at schedule_fail
  teuthology/suite/__init__.py
  teuthology/suite/run.py
  teuthology/suite/test/test_init.py
  teuthology/suite/test/test_run_.py
  teuthology/suite/test/test_util.py
  teuthology/suite/util.py
Labels: needs-qa, improvement
