Repository ceph/teuthology, pull requests merged in 2023-08, with the labels that each got.

#1881 stdin-killer: do not setpgrp is already leader
  teuthology/task/install/bin/stdin-killer
Labels: bug, needs-review

#1885 Fix docs build
  setup.cfg
  tox.ini
Labels: improvement, ci/cd

#1884 teuthology/scrape: Fix bad backtrace parsing in Teuthology.log
  teuthology/scrape.py
Labels: bug
